[project]
name = "aistudy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dashscope>=1.23.5",
    "ipykernel>=6.29.5",
    "python-dotenv>=1.1.0",
]
